### ISSUE TITLE
Review mlr3 cheatsheet

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3cheatsheets#2]
# General

- [x]  Cheatsheets usually contain no hyperlinks as one of their main purposes is the printed version (i.e. the "mlr3book" link and "mlr-org" link)

- [x] Use grey background for inline code formatting, e.g. `mlr task` is hard to distinguish between code and normal text

- [x] replace www.mlr-org.com by https://mlr-org.com 

- [x] reduce header height for more content space?
- [x] Change font to roboto

# Packages

- [x] The "Packages" section should only contain the "core" packages and also name them like that. I.e. no survival and ordinal. And possibly provide a link to the overview of all extension packages

# Intro & Workflow

- [x] "The mlr3 package provides R6 classes for the essential
building blocks of this machine learning workflow:" 
  - R6 is only the system behind, so better say "builds on R6 classes" or similar
  - "this machine learning workflow" -> "a common machine learning workflow"

- [x] Rather than starting all listings with "A [...]" just do "Task: Encapsulates [...]"

- [ ] maybe "encapsulates" is too techy here, rephrase?

- [ ] ~~color the workflow boxes?~~ Replace workflow figure

# Task

-  [ ] ~~"If you simply provide the dataset, it is automatically
converted to a DataBackendDataTable." -> The default backend is "DataBackendDataTable". 
  Then, list all other available backends in a list?~~ We do not have space for this. I removed this part completely. I think this is not of interest for the normal user. 
 
- [ ] Before starting with code, add a heading like "examples"

- [x] `TaskRegr$newt(backend, target)` <- typo

- [x] "For classification, the name of the target column is a label with only few distinct values." -> sounds more special than it is. Maybe just write something like "for classif, `target` is a character vectors with representing class labels"?

- [x] Rather than showing all methods, show the output of an example task? There are too many methods for a task and it gets boring quite quickly. Also all of this is in more detail in the help page whereas the output of a created task is not.

# Learner

- [x] ~~Show mlr_learners dictionary?~~ Replace all dictionaries with sugar

- [x] Mention and link to mlr3learners org and custom learners?

- [ ] "Get learner by key and construct the learner with specific
hyperparameter and settings (...) in one go." -> Do not show a generic way but rather a concrete example.

# Train & predict

- [ ] Show a train-predict workflow example rather than a generic example

# Resampling

- [x] "Resampling is used to assess the performance of a learning algorithm." -> mention "cross-validation" somewhere here

- [x] shortly explain the difference/similarity between resample/cross-validation

- [x] mention that multiple train&predict calls are done during resampling

# Benchmarking

- [x] Remove `expand_grid()` 

- [x] I know, not much space left, but maybe also show the output of a BMR?

**Comment by sumny** [comment]
Two things i noticed when drafting the mlr3pipelines cheatsheet:

1. %>>% as a font (output) encoding is missing.
2. Underscores in code blocks are not copyable on my machine.

**Comment by be-marc** [comment]
@sumny 2. should be fixed

**Comment by be-marc** [comment]
@pat-s 

> maybe "encapsulates" is too techy here, rephrase?

I do not like this word too. However, maybe we should stay in line with the book?

> Show a train-predict workflow example rather than a generic example

> "Get learner by key and construct the learner with specific
hyperparameter and settings (...) in one go." -> Do not show a generic way but rather a concrete example.

I think we should stay generic through the whole cheatsheet except for the `BenchmarkResult`

> Rather than showing all methods, show the output of an example task? There are too many methods for a task and it gets boring quite quickly. Also all of this is in more detail in the help page whereas the output of a created task is not.

I removed many of the methods but an example task might be too wide for a column

> Before starting with code, add a heading like "examples"

Do we really need this? We do not have much space ;)

**Comment by be-marc** [comment]
@sumny 1. It should work now?

**Comment by sumny** [comment]
@be-marc yes, both seems to be fine now, I guess simply using T1 fontenc fixed it. Thanks!
